name: app2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  flutter_tabler_icons: ^1.43.0
  dio: ^5.4.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


flutter_native_splash:
  color: "#FF5252"  # El color de fondo de tu pantalla de inicio (puede ser cualquier color hexadecimal)
  image: assets/toolbox.png  # La imagen de tu splash screen (asegúrate de tenerla en la carpeta correcta)
  android_12: 
    image: assets/toolbox.png 
    color: "#FF5252"
    icon_background_color: "#111111"     # Si no quieres soporte para la web
